### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by jackychee** [megnliren/music#1]
I want to learn vue, and i found this amazing project, can you introduce how to run this app in HOME.md？
that will help   @#me a lot.

**Comment by megnliren** [comment]
Build Setup

# install dependencies
npm install

# serve with hot reload at localhost:8080
npm run dev

# build for production with minification
npm run build

# build for production and view the bundle analyzer report
npm run build --report

**Comment by jackychee** [comment]
Thanks
